# version: '3.8'
# services:
#   api:
#     build:
#       context: .
#       dockerfile: docker/Dockerfile
#     ports:
#       - "8000:8000"
#     depends_on:
#       - db
#       - kafka

#   db:
#     image: postgres:15
#     environment:
#       POSTGRES_DB: marketdb
#       POSTGRES_USER: user
#       POSTGRES_PASSWORD: password
#     ports:
#       - "5432:5432"

#   zookeeper:
#     image: confluentinc/cp-zookeeper:latest
#     environment:
#       ZOOKEEPER_CLIENT_PORT: 2181

#   kafka:
#     image: confluentinc/cp-kafka:latest
#     ports:
#       - "9092:9092"
#     environment:
#       KAFKA_BROKER_ID: 1
#       KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#       KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
#       KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

#   # adminer:
#     image: adminer
#     restart: always
#     ports:
#       - 8080:8080

# version: '3.9'

services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
      - kafka
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/marketdb

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: marketdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080